POST http://localhost:8000/api/url/shorten
Content-Type: application/json

{
    "longUrl": "https://strawhatdeveloper.hashnode.dev/into-the-compose-verse-a-beginners-guide-to-jetpack-compose-state-management#comments-list"
}